name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            set -e

            APP_DIR="/var/www/marras-barrels"
            SERVICE_NAME="marras-barrels"

            echo "Deploying to $APP_DIR..."

            # Create directory if it doesn't exist
            sudo mkdir -p $APP_DIR
            sudo chown $USER:$USER $APP_DIR

            # Clone or pull latest code
            if [ -d "$APP_DIR/.git" ]; then
              echo "Pulling latest changes..."
              cd $APP_DIR
              git pull origin main
            else
              echo "Cloning repository..."
              git clone https://github.com/dutchiono/marras-barrels.git $APP_DIR
              cd $APP_DIR
            fi

            # Install dependencies if needed
            if [ -f "package.json" ]; then
              echo "Installing dependencies..."
              npm install --production
            fi

            # Restart service
            echo "Restarting $SERVICE_NAME service..."
            sudo systemctl restart $SERVICE_NAME
            sudo systemctl status $SERVICE_NAME --no-pager

            echo "Deployment complete!"